name: Generate and Deploy Report

on:
  push:
    branches: [main]  # or use workflow_dispatch for manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate Report
        run: |
          mkdir -p output
          echo "<html><body><h1>Test Report</h1><p>Generated at $(date)</p></body></html>" > output/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
