name: Build and Deploy Report

on:
  push:
    branches: [main]

jobs:
  generate-report:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.set-output.outputs.artifact-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate HTML Report
        run: |
          mkdir -p report
          echo "<html><body><h1>My Report</h1><p>Generated on $(date)</p></body></html>" > report/index.html

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: report/

  deploy-report:
    needs: generate-report
    runs-on: ubuntu-latest
    steps:
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: html-report
          path: output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHP_TOKEN }}
          publish_dir: ./output